package deaktator.pops

/**
  * Protocol Buffers deal with enumerated types in a special way.  To handle this, an
  * [[deaktator.pops.enums.EnumProtoOps]] type class provides accessor to static methods
  * available to enumerated types generated by Protocol Buffers java compiler.
  */
package object enums
